services:
  # 1. Application Server
  #  app:
  #    build: .
  #    container_name: muroom-backend-bach
  #    restart: always
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      # Spring Profile
  #      - SPRING_PROFILES_ACTIVE=local
  #      # DB Connection
  #      - DB_HOST=localhost
  #      - DB_PORT=5432
  #      - DB_NAME=muroomdb
  #      - DB_USERNAME=muroomadmin
  #      - DB_PASSWORD=muroom1234
  #      # Valkey(Redis) Connection
  #      - VALKEY_HOST=valkey
  #      - VALKEY_PORT=6379
  #      - VALKEY_USERNAME=muroomadmin
  #      - VALKEY_PASSWORD=muroom1234
  #    depends_on:
  #      - postgres
  #      - valkey
  #    networks:
  #      - muroom-network

  # 2. Database (Postgres 17 + PostGIS 3.5)
  db:
    image: kartoza/postgis:17-3.5
    container_name: muroom-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: muroomadmin
      POSTGRES_PASSWORD: muroom1234
      POSTGRES_DB: muroomdb
      TZ: UTC
    volumes:
      - ${HOME}/muroom/development/docker-volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - muroom-network

  # 3. Valkey (Redis 호환 인메모리 데이터베이스)
  valkey:
    image: valkey/valkey:8.1.5
    container_name: muroom-valkey
    restart: always
    ports:
      - "6379:6379"
    command: valkey-server /usr/local/etc/redis/valkey.conf
    volumes:
      - ${HOME}/muroom/development/docker-volumes/valkey_data:/data
      - ./valkey/valkey.conf:/usr/local/etc/redis/valkey.conf
      - ./valkey/users.acl:/usr/local/etc/redis/users.acl
    networks:
      - muroom-network

# 볼륨 정의 (데이터 보존용)
volumes:
  postgres_data:
  redis_data:

# 네트워크 정의 (컨테이너끼리 통신용)
networks:
  muroom-network:
    driver: bridge