spring:
  application:
    name: muroom-backend-bach
  mvc:
    servlet:
      load-on-startup: 1

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics # 헬스, 정보, 메트릭만 노출
  endpoint:
    health:
      show-details: when_authorized # 상세 정보(DB 연결 상태, 디스크 공간 등)를 보여줌. (보안상 운영에선 when_authorized 권장이나 내부망이면 always도 가능)
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

cors:
  allowed-origins: "http://localhost:3000,http://localhost:3001,https://muroom.kr,https://www.muroom.kr,https://admin.muroom.kr,https://muroom-frontend-handel-web.vercel.app,https://admin.muroom.kr,https://dev.admin.muroom.kr,
https://dev-api.muroom.kr"

seoul:
  api:
    key: ${SEOUL_API_KEY}

juso:
  api:
    search-key: ${JUSO_SEARCH_API_KEY}
    coord-key: ${JUSO_COORD_API_KEY}

kakao:
  api:
    rest-api-key: ${KAKAO_REST_API_KEY}

springdoc:
  version: v25.12.02
  title: Muroom API Docs
  description: Muroom 프로젝트 API 명세서입니다. 'Authorize' 버튼을 눌러 JWT 토큰을 입력해주세요.
  swagger-ui:
    path: /docs
    display-request-duration: true
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: alpha
  paths-to-match:
    - /api/v1/**
#    - /api/v2/**
#    - /api/v3/**