spring:
  application:
    name: muroom-backend-bach

cors:
  allowed-origins: "http://localhost:3000,http://localhost:3001,https://muroom.kr,https://www.muroom.kr,https://admin.muroom.kr,https://muroom-frontend-handel-web.vercel.app"

seoul:
  api:
    key: ${SEOUL_API_KEY}

juso:
  api:
    search-key: ${JUSO_SEARCH_API_KEY}
    coord-key: ${JUSO_COORD_API_KEY}

kakao:
  api:
    rest-api-key: ${KAKAO_REST_API_KEY}

springdoc:
  version: v25.12.02
  title: Muroom API Docs
  description: Muroom 프로젝트 API 명세서입니다. 'Authorize' 버튼을 눌러 JWT 토큰을 입력해주세요.
  swagger-ui:
    path: /docs
    display-request-duration: true
    groups-order: DESC
  paths-to-match:
    - /api/v1/**
#    - /api/v2/**
#    - /api/v3/**