spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/muroomdb
    username: muroomadmin
    password: local-postgres-password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 60000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: false
    #baseline-on-migrate: true
    #locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379
      password: local-redis-password

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    secretsmanager:
      enabled: true
    credentials:
      instance-profile: true
    stack:
      auto: false
    s3:
      private-bucket-name: ${AWS_S3_PRIVATE_BUCKET}
      public-bucket-name: ${AWS_S3_PUBLIC_BUCKET}
      presign:
        expiration: 10m

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration-ms: 2592000000 #15분은 900000ms
  refresh-expiration-ms: 3600000 # 1시간
  signup-expiration-ms: 900000

logging:
  level:
    org.springframework: INFO
    kr.muroom.muroombackendbach: DEBUG

server:
  url: http://localhost:8080
  forward-headers-strategy: native
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}


ncp:
  sens:
    access-key: ${NAVER_ACCESS_KEY_ID}
    secret-key: ${NAVER_SECRET_KEY}
    service-id: ${NAVER_SENS_SERVICE_ID}
    from: ${NAVER_SENS_FROM}


withdrawal:
  hard-delete:
    batch-size: 10
    max-loop: 200