ALTER TABLE studio_building_info ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE studio_building_info ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE studio_building_info ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE studio_forbidden_instruments ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE studio_forbidden_instruments ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE studio_forbidden_instruments ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE studio_images ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE studio_images ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE studio_images ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE studio_options ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE studio_options ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE studio_options ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE studio_prices ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE studio_prices ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE studio_prices ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE subway_stations_nearby_studios ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE subway_stations_nearby_studios ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE subway_stations_nearby_studios ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
